version: '3.8'

services:
  node:
    build: 
      context: .
      dockerfile: docker/node/Dockerfile 
    ports:
      - "3333:3000" 
    depends_on:
      - postgres  
    env_file:
      - .env.production.local
    networks:
      - nest_network

  postgres:
    build: 
      context: .
      dockerfile: docker/postgres/Dockerfile
    env_file:
      - .env.production.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest_network

  nginx:
    image: nginx:1.27.2
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - nest_network

networks:
  nest_network:
    driver: bridge

volumes:
  pgdata: